export const colors = {
  background: '#F4F7FB',
  surface: '#FFFFFF',
  text: '#172033',
  muted: '#667085',
  border: '#DCE3ED',
  primary: '#3157D5',
  primaryLight: '#EAF0FF',
  danger: '#B42318',
  dangerLight: '#FEF3F2',
  success: '#067647',
  successLight: '#ECFDF3',
  warning: '#B54708',
  warningLight: '#FFFAEB',
};

export const common = {
  page: { flex: 1, backgroundColor: colors.background },
  content: { padding: 20, paddingBottom: 36 },
  title: { color: colors.text, fontSize: 26, fontWeight: '800', marginBottom: 6 },
  subtitle: { color: colors.muted, fontSize: 15, marginBottom: 18 },
  label: { color: colors.text, fontSize: 14, fontWeight: '700', marginBottom: 7 },
  input: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: 1,
    color: colors.text,
    fontSize: 16,
    marginBottom: 16,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  button: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 12,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
  },
  buttonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  secondaryButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 11,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 13,
  },
  secondaryButtonText: { color: colors.primary, fontSize: 14, fontWeight: '700' },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 12,
    padding: 16,
  },
  row: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
};
